language: objective-c
osx_image: xcode10.1
xcode_workspace: MeowlWatch.xcworkspace
xcode_scheme: MeowlWatch
platform: iOS Simulator,OS=12.1,name=iPhone 8 Plus

script:
  - set -o pipefail
  - xcodebuild -sdk iphonesimulator -workspace MeowlWatch.xcworkspace -scheme MeowlWatch build test | xcpretty
