language: objective-c
osx_image: xcode11.0
xcode_workspace: MeowlWatch.xcworkspace
xcode_scheme: MeowlWatch
platform: iOS Simulator,OS=13.0,name=iPhone 11 Pro Max

before_script:
  - cp MeowlWatch/AdMobKeys-Debug.plist MeowlWatch/AdMobKeys-Release.plist

script:
  - set -o pipefail && xcodebuild -sdk iphonesimulator -workspace MeowlWatch.xcworkspace -scheme MeowlWatch build | xcpretty
